# Generated by Django 4.0.4 on 2022-04-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('incorrect_answer1', models.CharField(blank=True, max_length=255)),
                ('incorrect_answer2', models.CharField(blank=True, max_length=255)),
                ('incorrect_answer3', models.CharField(blank=True, max_length=255)),
                ('correct_answer', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
